// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBamZsq2EgQ9EJ80-sj0k3ExM92kH5LUzw',
    appId: '1:260911152312:web:3b87d0221ad2a88cd1c84d',
    messagingSenderId: '260911152312',
    projectId: 'leakagedetection-3b460',
    authDomain: 'leakagedetection-3b460.firebaseapp.com',
    databaseURL: 'https://leakagedetection-3b460-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'leakagedetection-3b460.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD67owoeEAaicFwykTma2zs4dI3oeuTdLw',
    appId: '1:260911152312:android:5b71cbe3cb519d9dd1c84d',
    messagingSenderId: '260911152312',
    projectId: 'leakagedetection-3b460',
    databaseURL: 'https://leakagedetection-3b460-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'leakagedetection-3b460.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbx9GBh1XAHQXcMDDUI3vMeNZul5r60u4',
    appId: '1:260911152312:ios:663aadeb0161f571d1c84d',
    messagingSenderId: '260911152312',
    projectId: 'leakagedetection-3b460',
    databaseURL: 'https://leakagedetection-3b460-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'leakagedetection-3b460.appspot.com',
    iosBundleId: 'com.example.leakagedetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbx9GBh1XAHQXcMDDUI3vMeNZul5r60u4',
    appId: '1:260911152312:ios:663aadeb0161f571d1c84d',
    messagingSenderId: '260911152312',
    projectId: 'leakagedetection-3b460',
    databaseURL: 'https://leakagedetection-3b460-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'leakagedetection-3b460.appspot.com',
    iosBundleId: 'com.example.leakagedetection',
  );
}
